### ISSUE TITLE
Increase default timeout

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#18]
Should we increase the default timeout? From 10 to 20? I noticed this seems to significantly decrease the number of timed out sites. For example, 20% of sites from the most recent scheduled crawl errored (about 2/3 of that are timeouts, or something like that). (Do we have any historical logs to see what the timeout rate is generally? Would be useful for gauging effectiveness.)

Fewer sites timing out should mean more stability to crawl results which means more meaningful comparisons between runs.

**Comment by ghostwords** [comment]
Finished running a 2,000 site crawl with timeout set to 20 seconds. Ran for just over 8.5 hours.

330 sites errored, a 16.5% error rate. Better than 20%, but still high!

Let's look at the error breakdown:

- 86 "timeout on" timeouts (we're double counting here I think, often both the https and http version of the same domain time out)

The rest are "WebDriverException: Reached error page" Firefox error pages:

- 117 DNS not found errors
- 83 netTimeouts (how are these different from "timeout on"?)
- 79 connection failures
- 13 misc. SSL errors
- 8 server resets
- 3 connection interrupted errors
- 2 redirect loops
- 1 unknown protocol

Total Firefox error page count: 306. If 330 sites errored according to log output at the end, this leaves us with only 24 "timeout on" sites, which doesn't make sense given the 86 "timeout on" instances in the log. Not clear yet where the counting went wrong.

**Comment by ghostwords** [comment]
Latest scheduled run claims a ~20% error rate again:
>Visited 1607 sites and errored on 393.

**Comment by bcyphers** [comment]
We should look into #21 more, but in the meantime I think it's harmless to do this too.

**Comment by bcyphers** [comment]
Closed with 13c252d050014145b7e95820067922def4e0876b

**Comment by bcyphers** [comment]
In the latest scan, after merging #23 and increasing the timeout, there were 273 errors (13%).
