### ISSUE TITLE
Should we reduce the number of sites we run on for now?

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#2]
To balance effectiveness against shipping buggy data ([heuristic + bug label search results](https://github.com/EFForg/privacybadger/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Aheuristic+label%3Abug)), ease of running crawler, ability to run crawler daily, size of seed database. We could always increase size of seed db later as we fix bugs (and multi-process/parallelize the crawler). Just want to start easier.

**Comment by bcyphers** [comment]
Closed with ab37153
