### ISSUE TITLE
docker build failed - missing domain-lists file

### ISSUE THREAD

**Issue by iammyr** [EFForg/badger-sett#28]
When running ./runscan.sh for the first time, I was getting the following error

`Step 23/28 : COPY domain-lists $HOME/domain-lists
COPY failed: stat /var/lib/docker/tmp/docker-builder530191829/domain-lists: no such file or directory
Docker build failed.
`

**Comment by ghostwords** [comment]
@bcyphers What are `domain-lists`? Should they just be removed from the Dockerfile?

**Comment by bcyphers** [comment]
those are so that you can specify your own lists of domains to scan for. it's supposed to be a directory, which can be empty. I think we can put that line behind a check for existence.

**Comment by ghostwords** [comment]
Ah OK. Was this fixed by 7acececc0434fb730f03fe450b021e6eb8820f45?

**Comment by ghostwords** [comment]
Also, how do `domain-lists` get used?

**Comment by bcyphers** [comment]
we've used them internally for a few different things, like scanning lists of the top sites from different countries. It's not used in the daily scan.

**Comment by bcyphers** [comment]
and yeah, 7acececc should have fixed this!
