### ISSUE TITLE
Review cleanup code

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#3]
Used for a43c06e4bd9a42ad6c31f80387c22f66b1e5e905. Probably makes sense to keep it here as a post-processing step.

**Comment by bcyphers** [comment]
Added in 7b0243f662d96ac5c143f7cd9d64af756ef3116a. Let me know what you think.

**Comment by bcyphers** [comment]
We should consider using the heuristic here to work around the misattribution problem in Privacy Badger, https://github.com/EFForg/privacybadger/issues/1997 that's holding back https://github.com/EFForg/privacybadger/pull/2024. 

That is: have Privacy Badger store information about the last domain that the user visited with their browser. If it appears that the previous domain is "tracking" the user on the next domain they visit, ignore that tracking action.
