### ISSUE TITLE
docker build failed - hardcoded username

### ISSUE THREAD

**Issue by iammyr** [EFForg/badger-sett#30]
The username and group for the chown command on privacybadger in the dockerfile are hardcoded (as "bennett") and are causing the docker build to fail with the following:
`Step 25/28 : COPY --chown=bennett:bennett privacybadger $PBPATH
unable to convert uid/gid chown string to host mapping: can't find uid for user bennett: no such user: bennett
Docker build failed.
`

**Comment by ghostwords** [comment]
Is this fixed by #48?

**Comment by bcyphers** [comment]
yep. Closed by #48.
