### ISSUE TITLE
What is the DNS Server to use?

### ISSUE THREAD

**Issue by funilrys** [EFForg/badger-sett#44]
Hello,
since you introduced PyFunceble (note that #21 might be closed) into #23, followed by the merge of the maintenances PR I submitted (#39 #40), I'm now wondering which DNS Server you recommend or use?

I'm mainly asking so I can write a PR because, since the last version of PyFunceble (2.0.0) which I released yesterday (Berlin Time), it's possible to set a custom DNS server for the DNS Lookup PyFunceble does.

- More info about the new version can be found into the [2.0.0 release note](https://github.com/funilrys/PyFunceble/releases/tag/2.0.0).

- More info about the custom DNS in PyFunceble can be found in the new version of [the documentation](https://pyfunceble.readthedocs.io/en/latest/components/custom-dns-server.html). 

For our implementation in this project, the following (pseudo) line:

```json
"dns_server": ["first_dns_server", "second_dns_server"]
```

might be added to this dictionary:
https://github.com/EFForg/badger-sett/blob/38b36818d3c8627302a874e072c2494e35cad02f/crawler.py#L46

As a side note, I dropped the logs sharing by default. So `"share_logs": False` might not be needed but we can keep it if we choose to use `PyFunceble<2.0.0` instead of the newly released one.

Have a nice day/night.

Cheers,
Nissar

**Comment by ghostwords** [comment]
Hi, sorry for the late reply! We switched to the [Tranco list](https://tranco-list.eu/) (#45), which seems to mostly obviate the need to validate domains ourselves.
