### ISSUE TITLE
Add an option to specifically exclude or include user-provided TLDs

### ISSUE THREAD

**Issue by jgillula** [EFForg/badger-sett#47]
We should add the ability to either exclude or include specific user-provided TLDs when we do the scan. That way, if we don't want to scan domains in certain TLDs the user can configure that when they run the scan; or if, a user *only* wants to scan domains in a given TLD, they can do that instead.

**Comment by jgillula** [comment]
BTW, I'm totally ambivalent how this is specified--in a config file, or as a command-line option, or via a Matrix-like virtual reality interface... ;-)

**Comment by ablanathtanalba** [comment]
This should be even easier if we do decide to roll with the tranco list instead of the majestic million
