### ISSUE TITLE
Log Privacy Badger branch and commit hash

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#52]
Branch for human readability and hash for exactness. Logging the hash will make it possible to know precisely which Privacy Badger code was exercised by the scan.

**Comment by ghostwords** [comment]
Let's also log the browser version.

**Comment by ablanathtanalba** [comment]
Just to clarify -- you think this should be logged in the statements that print out on every run, or just in the `--log-stdout` output if that option is passed?

**Comment by ghostwords** [comment]
`--log-stdout` doesn't change what is logged, just how it is logged.

**Comment by ablanathtanalba** [comment]
Ah, right thank you!
