### ISSUE TITLE
Allow loading of arbitrary extensions

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#54]
Now that we can run scans to evaluate the effect of (strict) Tracking Protection on Privacy Badger's learning (c6c932ef82b1c58f1714e8653177a80198ca966f), it would be nice to also have the ability to load arbitrary other extensions to make similar comparisons. So, a `--load-extension` flag.

Loading packed extensions in Chrome should be simple with `opts.add_extension(PATH_TO_EXTENSION_CRX)`. Firefox is probably more complicated, so I suggest getting this working on Chrome first.

**Comment by ghostwords** [comment]
Firefox should now support simple loading of packed and unpacked extensions too. I updated the master branch to load Privacy Badger (unpacked): f7596b1393a8c637e89235ba7905a44c1b5046c0

**Comment by ablanathtanalba** [comment]
> Firefox should now support simple loading of packed and unpacked extensions too. I updated the master branch to load Privacy Badger (unpacked): [f7596b1](https://github.com/EFForg/badger-sett/commit/f7596b1393a8c637e89235ba7905a44c1b5046c0)

Great, I can add that into the WIP PR
