### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by MrBrain295** [EFForg/badger-sett#76]
When I try to run it I get this error `ERROR: failed to solve: failed to parse stage name "selenium/standalone-/vscode/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/helpers/browser.sh": invalid reference format
Docker build failed.`

**Comment by ghostwords** [comment]
Does this happen during `docker build`? It looks like your `"$BROWSER"` environment argument isn't set.

https://github.com/EFForg/badger-sett/blob/5837e2d080a2265c73210b2bb1764cf9f0824096/runscan.sh#L74-L75

https://github.com/EFForg/badger-sett/blob/5837e2d080a2265c73210b2bb1764cf9f0824096/Dockerfile#L4

And then Docker looks for `"selenium/standalone-/..."` where it should be looking for `"selenium/standalone-firefox/..."` or whatever .

I think our README is confusing and/or missing some information. Sorry about that!

You should be able to fix your error by prepending your `runscan.sh` command with `BROWSER=chrome` (or `firefox`, or `edge`).

You can also run `crawler.py` directly without Docker, you'll just have to set up your pip environment from `requirements.txt` and check out the Privacy Badger repository yourself and provide a bunch of arguments to `crawler.py`. For example:

```bash
$ ./crawler.py --num-sites 20 --browser chrome --pb-dir ../privacybadger --take-screenshots --log-stdout
```

Let me know if you have any questions.

**Comment by MrBrain295** [comment]
That worked. Thank you!
