### ISSUE TITLE
in crawler.py NUM_SITES = 2000?  Is this how many Privacy Badger currently trains upon?

### ISSUE THREAD

**Issue by jawz101** [EFForg/badger-sett#77]
Can you all raise it to 100,000, a million, or as many as possible?  It seems awfully low if users are not training each of their extensions against their own browsing habits.

The value of a tracker's tracking depends on each person's unique due browsing habits.  It makes sense to train on the maximum amount of sites as possible rather than limiting the data set to 2000 most commonly visited sites.

I can think of car dealerships, smaller storefronts, travel sites, and local news sites with loads of trackers that are not likely in the top 2000 sites in the world.

I just opened up all of my bookmarks and privacy badger learned a new tracking domain.
I'd argue simply visiting a website is not enough.  If I owned a shopping store, my trackers might not be on the main page.  I would want to track each product that was clicked upon which may mean my trackers are on each product page.   If the test emulated clicking on a few product pages, you may find a different set of trackers on each product page.

**Comment by ghostwords** [comment]
Hello!

[Previous discussion](https://github.com/EFForg/badger-sett/issues/61#issuecomment-827966974).

We attempt to visit [30K sites at this point](413ac752edef156689eed0dfe0bde442e7d9cfa5). The plan is to continue to gradually increase the scope.

If we increase our training scope too quickly, we will have to deal with too man false positives and too many broken sites.

Check out [our recent blog post](https://www.eff.org/deeplinks/2023/10/privacy-badger-learns-block-ever-more-trackers) about the evolution of Privacy Badger's learning.

**Comment by ghostwords** [comment]
We do already [attempt to identify and visit "news" links](https://github.com/EFForg/badger-sett/issues/61#issuecomment-827970520). Good idea about doing the same for product pages.

**Comment by jawz101** [comment]
is it still looking at only the top 2000 sites?  Because that is not enough

**Comment by ghostwords** [comment]
>Is it still looking at only the top 2000 sites?

Did you see my earlier response? We're up to 30,000 and climbing.
