### ISSUE TITLE
Using own lists and not be bound to "Tranco List"

### ISSUE THREAD

**Issue by spirillen** [EFForg/badger-sett#86]
As I have been reading the weak README on how project can be used to crawl for trackers, I come to the question, Can I tell it to crawl from one of my own (set of) lists? Here I do have my NSFW[1] lists in mind as they are among the fastest to adopt new stuff

- [1] https://github.com/mypdns/matrix/tree/master/source

Is there a better documentation some where on how this project can be used?

**Comment by ghostwords** [comment]
You're looking for the `--site-list` argument. The arguments are documented in `./crawler.py --help` (step 6 of [development setup](https://github.com/EFForg/badger-sett?tab=readme-ov-file#development-setup)). Let me know if you run into trouble following the steps.

**Comment by spirillen** [comment]
Super, thanks for your reply, I will play with it later 👍🏻
